### ISSUE TITLE
`unsafe` prefix in table headers

### ISSUE THREAD

**Issue by BonaBeavis** [dathere/datapusher-plus#93]
**Describe the bug**
Push this https://statistik.leipzig.de/opendata/api/kdvalues?kategorie_nr=15&rubrik_nr=2&periode=d&format=csv

Then the headers are prepended with unsafe, is it possible to disable this?

**Comment by jqnatividad** [comment]
Hi @BonaBeavis ,
This is because DP+ sanitizes the column names of CSVs to ensure that they're not only valid PostgreSQL identifiers, but is usable from the API as well.

Technically, just about any string can be made valid by using quoted identifiers in PostgreSQL - but it has the undesired side-effect of making it harder to use.
https://lerner.co.il/2013/11/30/quoting-postgresql/

Perhaps, you can change the column names before uploading them?

If that's not possible, would adding an alternate prefix other than "unsafe" to DP+ configuration be enough?  That functionality is already supported by qsv but is not exposed in DP+.

**Comment by jqnatividad** [comment]
The strings need to be valid UTF-8 and considered to be a valid Postgres identifier without having to quote it.

See https://github.com/jqnatividad/qsv/blob/master/src/cmd/safenames.rs#L2 to find out how column names are sanitized.

For more info on what makes a valid unquoted Postgres identifier, see https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS for details.

**Comment by BonaBeavis** [comment]
Can I just use an empty prefix?

**Comment by BonaBeavis** [comment]
Ok, I can use an empty prefix but this breaks the datapusher.

**Comment by jqnatividad** [comment]
I’m afraid you cannot use an empty prefix as it will still be invalid.
